### ISSUE TITLE
Throwing NotSupported exception on VS 2022 17.11.1

### ISSUE THREAD

**Issue by 77** [aberus/ImageVisualizer#20]
This was working previously but not working on Visual Studio Enterprise 2022 v17.11.1.

```
An unhandled exception of type 'System.NotSupportedException' was thrown by the custom visualizer component in the process being debugged.

This method is not supported when using the formatter policy 'Legacy'.

at Microsoft.VisualStudio.DebuggerVisualizers.VisualizerObjectSource.Serialize(Stream serializationStream, Object target)
   at Microsoft.VisualStudio.DebuggerVisualizers.VisualizerObjectSource.GetData(Object target, Stream outgoingData)
   at Aberus.VisualStudio.Debugger.ImageVisualizer.ImageVisualizerBitmapObjectSource.GetData(Object target, Stream outgoingData)
   at Microsoft.VisualStudio.DebuggerVisualizers.DebuggeeSide.Impl.ClrCustomVisualizerDebuggeeHost.GetData(Object visualizedObject)
```

**Comment by 77** [comment]
https://learn.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2022

Due to the security issues described in [Special debugger side considerations for .NET 5.0+](https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2022#special-debugger-side-considerations-for-net-50), starting with Visual Studio 2022 version 17.11, visualizers won't be able to specify the Legacy formatter policy.

**Comment by nikefa** [comment]
Hey 77, 
have you found a workaround for the problem?

**Comment by Joe-Fernico** [comment]
Unfortunately, I ended up using another Debug Image Viewer. Not sure if it is bad taste to put the name here or not?

**Comment by nikefa** [comment]
I would be very grateful for the name^^
Currently I save the Bitmaps to view them

**Comment by Joe-Fernico** [comment]
https://marketplace.visualstudio.com/items?itemName=KGySoft.drawing-debugger-visualizers

**Comment by binbon2d** [comment]
> https://marketplace.visualstudio.com/items?itemName=KGySoft.drawing-debugger-visualizers

Same isssue ?

**Comment by aberus** [comment]
Here is a quick fix (It may or may not work 🚧), can you try and give a feedback if it solves this issue:
[SetupVisualizer.zip](https://github.com/user-attachments/files/17708368/SetupVisualizer.zip)

**Comment by aberus** [comment]
New version released with a fix.
